# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fbarriosCL
email: felipe@backtrackacademy.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Felipe Barrios CEO of Backtrack Academy Ethical Hacking E-learning. 
  Entrepreneur and back-end developer Ruby on Rails, Ror became my preferred language.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://backtrackacademy.com" # the base hostname & protocol for your site
twitter_username: FbarriosL
github_username:  fbarriosCL

# Build settings
markdown: kramdown
